# Problem 1

## Using GPU

In [1]:
%run extcode/DeepLearningTutorials/code/logistic_sgd.py

... loading data
... building the model
... training the model
epoch 1, minibatch 83/83, validation error 12.458333 %
     epoch 1, minibatch 83/83, test error of best model 12.375000 %
epoch 2, minibatch 83/83, validation error 11.010417 %
     epoch 2, minibatch 83/83, test error of best model 10.958333 %
epoch 3, minibatch 83/83, validation error 10.312500 %
     epoch 3, minibatch 83/83, test error of best model 10.312500 %
epoch 4, minibatch 83/83, validation error 9.875000 %
     epoch 4, minibatch 83/83, test error of best model 9.833333 %
epoch 5, minibatch 83/83, validation error 9.562500 %
     epoch 5, minibatch 83/83, test error of best model 9.479167 %
epoch 6, minibatch 83/83, validation error 9.322917 %
     epoch 6, minibatch 83/83, test error of best model 9.291667 %
epoch 7, minibatch 83/83, validation error 9.187500 %
     epoch 7, minibatch 83/83, test error of best model 9.000000 %
epoch 8, minibatch 83/83, validation error 8.989583 %
     epoch 8, minibatch 83/83,

Using gpu device 0: GRID K520
The code for file logistic_sgd.py ran for 7.1s


The code run for 74 epochs, with 10.414702 epochs/sec


In [2]:
%run extcode/DeepLearningTutorials/code/convolutional_mlp.py

... loading data
... building the model
... training
training @ iter =  0
epoch 1, minibatch 100/100, validation error 9.230000 %
     epoch 1, minibatch 100/100, test error of best model 9.540000 %
training @ iter =  100
epoch 2, minibatch 100/100, validation error 6.170000 %
     epoch 2, minibatch 100/100, test error of best model 6.480000 %
training @ iter =  200
epoch 3, minibatch 100/100, validation error 4.640000 %
     epoch 3, minibatch 100/100, test error of best model 4.840000 %
training @ iter =  300
epoch 4, minibatch 100/100, validation error 3.500000 %
     epoch 4, minibatch 100/100, test error of best model 3.930000 %
training @ iter =  400
epoch 5, minibatch 100/100, validation error 3.020000 %
     epoch 5, minibatch 100/100, test error of best model 3.270000 %
training @ iter =  500
epoch 6, minibatch 100/100, validation error 2.800000 %
     epoch 6, minibatch 100/100, test error of best model 2.810000 %
training @ iter =  600
epoch 7, minibatch 100/100, validation

The code for file convolutional_mlp.py ran for 8.69m


## Using CPU

In [3]:
%env THEANOFLAGS=device=cpu

env: THEANOFLAGS=device=cpu


In [4]:
%run extcode/DeepLearningTutorials/code/logistic_sgd.py

... loading data
... building the model
... training the model
epoch 1, minibatch 83/83, validation error 12.458333 %
     epoch 1, minibatch 83/83, test error of best model 12.375000 %
epoch 2, minibatch 83/83, validation error 11.010417 %
     epoch 2, minibatch 83/83, test error of best model 10.958333 %
epoch 3, minibatch 83/83, validation error 10.312500 %
     epoch 3, minibatch 83/83, test error of best model 10.312500 %
epoch 4, minibatch 83/83, validation error 9.875000 %
     epoch 4, minibatch 83/83, test error of best model 9.833333 %
epoch 5, minibatch 83/83, validation error 9.562500 %
     epoch 5, minibatch 83/83, test error of best model 9.479167 %
epoch 6, minibatch 83/83, validation error 9.322917 %
     epoch 6, minibatch 83/83, test error of best model 9.291667 %
epoch 7, minibatch 83/83, validation error 9.187500 %
     epoch 7, minibatch 83/83, test error of best model 9.000000 %
epoch 8, minibatch 83/83, validation error 8.989583 %
     epoch 8, minibatch 83/83,

The code for file logistic_sgd.py ran for 6.3s


In [5]:
%run extcode/DeepLearningTutorials/code/convolutional_mlp.py

... loading data
... building the model
... training
training @ iter =  0
epoch 1, minibatch 100/100, validation error 9.230000 %
     epoch 1, minibatch 100/100, test error of best model 9.540000 %
training @ iter =  100
epoch 2, minibatch 100/100, validation error 6.170000 %
     epoch 2, minibatch 100/100, test error of best model 6.480000 %
training @ iter =  200
epoch 3, minibatch 100/100, validation error 4.640000 %
     epoch 3, minibatch 100/100, test error of best model 4.840000 %
training @ iter =  300
epoch 4, minibatch 100/100, validation error 3.500000 %
     epoch 4, minibatch 100/100, test error of best model 3.930000 %
training @ iter =  400
epoch 5, minibatch 100/100, validation error 3.020000 %
     epoch 5, minibatch 100/100, test error of best model 3.270000 %
training @ iter =  500
epoch 6, minibatch 100/100, validation error 2.810000 %
     epoch 6, minibatch 100/100, test error of best model 2.810000 %
training @ iter =  600
epoch 7, minibatch 100/100, validation

The code for file convolutional_mlp.py ran for 8.67m


# Problem 2

## Create Matrix `X`

In [36]:
import theano
import theano.tensor as T

X = T.fmatrix('X')

## Create `A` and `b`

In [37]:
from theano.tensor.shared_randomstreams import RandomStreams
from time import time

srng = RandomStreams(seed=int(time()))
A, b = srng.uniform((10, 10)), srng.uniform((10, 1))

## Create function and recoders

In [38]:
from numpy import zeros

A_record, b_record = theano.shared(zeros((10, 10), dtype="Float32")), theano.shared(zeros((10, 1), dtype="Float32"))
f = theano.function([X], (X+A) * b, updates=((A_record, A_record+A), (b_record, b_record+b)))

## Evaluate

In [39]:
left = f(ones((10, 10), dtype='Float32'))
right = (ones((10, 10), dtype='Float32') + A_record.get_value()) * b_record.get_value()
print left - right

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
